name: Build and deploy code

on: ["push"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "hi user"
